#ifndef __RPGVXACE_H__
#define __RPGVXACE_H__

namespace RPGVXAce
{
    enum eCommandType {
        PTR_CALL_RPGVX_LOAD,
        PTR_CALL_RPGVX_SAVE,
        PTR_CALL_RPGVX_BATTLE_TEST_SAVE,
        PTR_CALL_RPGVX_BATTLE_TEST_DELETE,
        PTR_CALL_RPGVX_ADJUST1,
        PTR_CALL_RPGVX_ADJUST2,
        PTR_CALL_RPGVX_ADJUST3,
        PTR_CALL_RPGVX_ADJUST4,

        DEFINE_RPGVX_LOAD,
        DEFINE_RPGVX_SAVE,
        DEFINE_RPGVX_BATTLE_TEST_SAVE,
        DEFINE_RPGVX_BATTLE_TEST_DELETE,
        DEFINE_RPGVX_ADJUST1,
        DEFINE_RPGVX_ADJUST2,
        DEFINE_RPGVX_ADJUST3,
        DEFINE_RPGVX_ADJUST4,

        DEFINE_AND_CALL_RPGVX_SAVE_WITHOUT_SCRIPTS,

        DEFINE_DEEP_COPY,
        DEFINE_POSITION_BASE,
        DEFINE_IS_WORD,
        DEFINE_REMOVE_INSTANCE_VARIABLE,

        DEFINE_CLASS_RPG_MAP,
        DEFINE_CLASS_RPG_ACTOR,
        DEFINE_CLASS_RPG_CLASS,
        DEFINE_CLASS_RPG_ENEMY,
        DEFINE_CLASS_RPG_SKILL,
        DEFINE_CLASS_RPG_ITEM,
        DEFINE_CLASS_RPG_WEAPON,
        DEFINE_CLASS_RPG_ARMOR,
        DEFINE_CLASS_RPG_STATE,
        DEFINE_CLASS_RPG_SYSTEM,
        DEFINE_CLASS_DUNGEON_GENERATOR,

        DEFINE_SCRIPT_EDITOR_ACTION1,
        DEFINE_SCRIPT_EDITOR_ACTION2,
        DEFINE_SCRIPT_EDITOR_ACTION3,
        DEFINE_SCRIPT_EDITOR_ACTION4,
        DEFINE_SCRIPT_EDITOR_ACTION5,
        DEFINE_SCRIPT_EDITOR_ACTION6,
        DEFINE_SCRIPT_EDITOR_ACTION7,
        DEFINE_SCRIPT_EDITOR_ACTION8,
        DEFINE_SCRIPT_EDITOR_ACTION9,
        DEFINE_SCRIPT_EDITOR_ACTION10,
        DEFINE_SCRIPT_EDITOR_ACTION11,
        DEFINE_SCRIPT_EDITOR_ACTION12,
        DEFINE_SCRIPT_EDITOR_ACTION13,
        DEFINE_SCRIPT_EDITOR_ACTION14,
        DEFINE_SCRIPT_EDITOR_ACTION15,
        DEFINE_SCRIPT_EDITOR_ACTION16,
        DEFINE_SCRIPT_EDITOR_ACTION17,
        DEFINE_SCRIPT_EDITOR_ACTION18,
        DEFINE_SCRIPT_EDITOR_ACTION19,
        DEFINE_SCRIPT_EDITOR_ACTION20,
        DEFINE_SCRIPT_EDITOR_ACTION21,
        DEFINE_SCRIPT_EDITOR_ACTION22,
        DEFINE_SCRIPT_EDITOR_ACTION23,
        DEFINE_SCRIPT_EDITOR_ACTION24,
        DEFINE_SCRIPT_EDITOR_ACTION25,
        DEFINE_SCRIPT_EDITOR_ACTION26,
        DEFINE_SCRIPT_EDITOR_ACTION27,
        DEFINE_SCRIPT_EDITOR_ACTION28,

        SIZE
    };

    struct CommandInfo
    {
        eCommandType Type;
        int Offset;
        char Scripts[6144];
    };
}

#endif // __RPGVXACE_H__